services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: $123Secreto456$
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - entrenosnet

  api:  
    build:
      context: .
    container_name: entrenos-api
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    networks:
      - entrenosnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  entrenosnet:
    driver: bridge
