version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "123Secreto456_"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - entrenosnet

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: entrenos-api
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: dotnet EntrenosApp.API.dll
    networks:
      - entrenosnet

volumes:
  sql_data:

networks:
  entrenosnet:
