version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "123Secreto456_"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
  backend:
    image: jmjuan/backend-api:latest
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EntrenosDb;User Id=sa;Password=123Secreto456_;TrustServerCertificate=true;Encrypt=true
    ports:
      - "5000:8080"
  frontend:
    image: jmjuan/frontend-app:latest
    depends_on:
      - backend
    ports:
      - "80:80"
volumes:
  sql_data: